# Generated by Django 6.0.1 on 2026-03-05 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('duration', models.CharField(blank=True, help_text="Misal '1-2 minggu'", max_length=100)),
                ('price', models.CharField(help_text="Misal 'Start from Rp 300.000'", max_length=100)),
                ('is_open', models.BooleanField(default=True, help_text='Masih tersedia?')),
                ('system', models.CharField(blank=True, help_text="Misal 'Pre-order via WA'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'T_Product',
            },
        ),
        migrations.CreateModel(
            name='TM_Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'db_table': 'TM_Division',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TM_EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
                'db_table': 'TM_EventCategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TM_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'TM_Position',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TM_ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'TM_ProductCategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TM_ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'Product Status',
                'verbose_name_plural': 'Product Statuses',
                'db_table': 'TM_ProductStatus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('role_id', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Staff'), (3, 'Anggota')], default=3)),
                ('is_default_password', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'T_Account',
            },
        ),
        migrations.CreateModel(
            name='T_Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('address', models.TextField()),
                ('map_link', models.URLField(blank=True, help_text='Link Google Maps atau Waze')),
                ('contact_pdt', models.CharField(blank=True, help_text='Kontak Pendeta', max_length=100)),
                ('contact_ketua', models.CharField(blank=True, help_text='Kontak Ketua Jemaat', max_length=100)),
                ('other_contact', models.TextField(blank=True, help_text='Kontak lain jika ada')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='churches/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Church',
                'verbose_name_plural': 'Churches',
                'db_table': 'T_Church',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='T_Church_slug_c91d00_idx')],
            },
        ),
        migrations.CreateModel(
            name='T_ChurchService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nama ibadah, misal 'Ibadah Raya'", max_length=100)),
                ('day', models.CharField(help_text="Hari, misal 'Sabtu' atau 'Jumat Malam'", max_length=50)),
                ('time', models.CharField(help_text="Waktu, misal '08:00 - 10:00'", max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pagweb.t_church')),
            ],
            options={
                'verbose_name': 'Church Service',
                'verbose_name_plural': 'Church Services',
                'db_table': 'T_ChurchService',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='T_ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wa_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('request_type', models.CharField(choices=[('prayer', 'Prayer Request'), ('general', 'Pertanyaan Umum'), ('event', 'Informasi Event'), ('product', 'Product dan Layanan'), ('cooperation', 'Kerja Sama'), ('visit', 'Kunjungan'), ('other', 'Lainnya')], max_length=20)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
                'db_table': 'T_ContactRequest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='T_ContactRe_status_fb8ba0_idx'), models.Index(fields=['request_type'], name='T_ContactRe_request_5304f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='T_ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pagweb.t_product')),
            ],
            options={
                'verbose_name': 'Product Feature',
                'verbose_name_plural': 'Product Features',
                'db_table': 'T_ProductFeature',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='t_product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='pagweb.tm_productcategory'),
        ),
        migrations.AddField(
            model_name='t_product',
            name='statuses',
            field=models.ManyToManyField(blank=True, help_text='Bisa pilih lebih dari satu', related_name='products', to='pagweb.tm_productstatus'),
        ),
        migrations.CreateModel(
            name='T_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('date', models.DateField(help_text='Tanggal event')),
                ('time', models.CharField(blank=True, help_text='Contoh: 19:00 - 21:00 WIB', max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('pic_contact', models.CharField(blank=True, max_length=50, verbose_name='Contact Person (WA)')),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_closed', models.BooleanField(default=False, help_text='Centang jika pendaftaran ditutup manual')),
                ('is_featured', models.BooleanField(default=False, help_text='Tampilkan sebagai unggulan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='events', to='pagweb.tm_eventcategory')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'T_Event',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='T_Event_date_e0b601_idx'), models.Index(fields=['slug'], name='T_Event_slug_2eb582_idx'), models.Index(fields=['is_featured'], name='T_Event_is_feat_2ad7bc_idx'), models.Index(fields=['is_closed'], name='T_Event_is_clos_65f855_idx')],
            },
        ),
        migrations.CreateModel(
            name='T_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='pagweb.tm_division')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='pagweb.tm_position')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'T_Staff',
                'ordering': ['division__name', 'position__name', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='T_Staff_is_acti_87e818_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='t_product',
            index=models.Index(fields=['slug'], name='T_Product_slug_fd01ec_idx'),
        ),
        migrations.AddIndex(
            model_name='t_product',
            index=models.Index(fields=['is_open'], name='T_Product_is_open_2c3275_idx'),
        ),
    ]
