# Generated by Django 6.0.1 on 2026-03-05 14:37

import django.db.models.deletion
import pagweb.helperStorage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_church',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=pagweb.helperStorage.church_image_path),
        ),
        migrations.AlterField(
            model_name='t_event',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=pagweb.helperStorage.event_image_path),
        ),
        migrations.AlterField(
            model_name='t_product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=pagweb.helperStorage.product_image_path),
        ),
        migrations.AlterField(
            model_name='t_staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=pagweb.helperStorage.staff_image_path),
        ),
        migrations.CreateModel(
            name='T_EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pagweb.helperStorage.event_gallery_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pagweb.t_event')),
            ],
            options={
                'verbose_name': 'Event Media',
                'verbose_name_plural': 'Event Media',
                'db_table': 'T_EventMedia',
                'ordering': ['order', 'id'],
            },
        ),
    ]
